# Generated by Django 3.0.7 on 2020-06-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='docfile',
            field=models.FileField(default=1, upload_to='media/documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
