# Generated by Django 3.0.7 on 2020-06-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/%Y/%m/%d'),
        ),
    ]
